services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/sql_scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'

volumes:
  pgdata:
